# Generated by Django 6.0 on 2025-12-31 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(help_text='Ciri-ciri barang, warna, merek, dll.')),
                ('lokasi', models.CharField(help_text='Lokasi hilang atau ditemukan (Cth: Gedung B, Kantin)', max_length=100)),
                ('jenis', models.CharField(choices=[('KEHILANGAN', 'Saya Kehilangan Barang'), ('DITEMUKAN', 'Saya Menemukan Barang')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='gambar_barang/')),
                ('kontak_wa', models.CharField(help_text='Nomor WhatsApp yang bisa dihubungi', max_length=20)),
                ('tanggal_posting', models.DateTimeField(auto_now_add=True)),
                ('sudah_selesai', models.BooleanField(default=False, help_text='Centang jika barang sudah kembali/diambil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
