# Generated by Django 6.0 on 2026-01-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='kontak_wa',
            new_name='kontak_waaa',
        ),
    ]
