# Generated by Django 6.0 on 2026-01-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_kontak_wa_barang_kontak_waaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='kontak_waaa',
            new_name='kontak_wa',
        ),
    ]
